/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DoktorIslemleri;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.*;
import Helper.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author turanozturk
 */
public class DoktorlarGUI extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    DoktorIslemleri doktorIslemleri = new DoktorIslemleri();
    PoliklinikIslemleri poliklinikIslemleri = new PoliklinikIslemleri();
    Doktor selectedDoktor;
    ArrayList<Doktor> doktorlar;
    
    /**
     * Creates new form DoktorlarGUI
     */
    public DoktorlarGUI() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tableModel = (DefaultTableModel)tblDoktorlar.getModel();
        
        doktorlarTablo();
        
        if(doktorlar.size() != 0){
            tblDoktorlar.changeSelection(0, 0, false, false);
            selectedDoktor = doktorlar.get(0);
        }
      
        bilgiGetir(selectedDoktor);
        
        ArrayList<Poliklinik> poliklinikler_yd = poliklinikIslemleri.Listele("SELECT * FROM poliklinikler");
        for(Poliklinik poliklinik_yd : poliklinikler_yd){
            cmbPoliklinik_yd.addItem(poliklinik_yd.getPoliklinikAdi());
        }
        
    }
    
    public void doktorlarTablo(){
        tableModel.setRowCount(0);
        doktorlar = doktorIslemleri.Listele("SELECT * FROM doktorlar");
        if(doktorlar.size() != 0){
            int no = 0;
            for(Doktor doktor : doktorlar){
                Object[] row = { no + 1, doktor.getisimSoyisim(), poliklinikIslemleri.idToPoliklinik(doktor.getPoliklinikId()) };
                tableModel.addRow(row);
                no++;
            }
        }
    }

    public void bilgiGetir(Doktor doktor){
        
        if(doktor != null){
        
            tfIsimSoyisim_dd.setText(doktor.getisimSoyisim());
            tfTCKN_dd.setText(doktor.getTckn());
            SimpleDateFormat format1 = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date dogumTarihi = format1.parse(doktor.getDogumTarihi());
                dateDogumTarihi_dd.setDate(dogumTarihi);
            } catch (ParseException ex) {
                Logger.getLogger(DoktorlarGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            tfDoktorTelefon_dd.setText(doktor.getTelefon());
            if(doktor.getCinsiyet().equals("E")){
                rbErkek_dd.setSelected(true);
            }else{
                rbKadın.setSelected(true);
            }
            taAdres_dd.setText(doktor.getAdres());
            ArrayList<Poliklinik> poliklinikler = poliklinikIslemleri.Listele("SELECT * FROM poliklinikler");
            for(Poliklinik poliklinik : poliklinikler){
                cmbPoliklinik_dd.addItem(poliklinik.getPoliklinikAdi());
            }
            cmbPoliklinik_dd.setSelectedItem(poliklinikIslemleri.idToPoliklinik(doktor.getPoliklinikId()));
        
        }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpCinsiyet_dd = new javax.swing.ButtonGroup();
        btngrpCinsiyet_yd = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlDoktorlar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfArama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoktorlar = new javax.swing.JTable();
        pnlDoktorDuzenle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfIsimSoyisim_dd = new javax.swing.JTextField();
        tfTCKN_dd = new javax.swing.JTextField();
        tfDoktorTelefon_dd = new javax.swing.JTextField();
        rbErkek_dd = new javax.swing.JRadioButton();
        rbKadın = new javax.swing.JRadioButton();
        dateDogumTarihi_dd = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAdres_dd = new javax.swing.JTextArea();
        cmbPoliklinik_dd = new javax.swing.JComboBox<>();
        btnGuncelle_dd = new javax.swing.JButton();
        btnSil_dd = new javax.swing.JButton();
        pnlYeniDoktorEkle = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfIsımSoyisim_yd = new javax.swing.JTextField();
        tfTCKN_yd = new javax.swing.JTextField();
        tfTelefon_yd = new javax.swing.JTextField();
        rbErkek_yd = new javax.swing.JRadioButton();
        rbKadin_yd = new javax.swing.JRadioButton();
        dateDogumTarihi_yd = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAdres_yd = new javax.swing.JTextArea();
        cmbPoliklinik_yd = new javax.swing.JComboBox<>();
        btnEkle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASTANE - Doktorlar");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlDoktorlar.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoktorlar.setBorder(javax.swing.BorderFactory.createTitledBorder("Doktorlar"));

        jLabel1.setText("Arama : ");

        tfArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAramaActionPerformed(evt);
            }
        });
        tfArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAramaKeyReleased(evt);
            }
        });

        tblDoktorlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Doktor", "Poliklinik"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoktorlar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoktorlarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDoktorlar);
        if (tblDoktorlar.getColumnModel().getColumnCount() > 0) {
            tblDoktorlar.getColumnModel().getColumn(0).setResizable(false);
            tblDoktorlar.getColumnModel().getColumn(1).setResizable(false);
            tblDoktorlar.getColumnModel().getColumn(2).setResizable(false);
        }

        pnlDoktorDuzenle.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoktorDuzenle.setBorder(javax.swing.BorderFactory.createTitledBorder("Doktor Düzenle"));

        jLabel2.setText("İsim Soyisim : ");

        jLabel3.setText("T.C Kimlik No : ");

        jLabel4.setText("Doğum Tarihi : ");

        jLabel5.setText("Adres : ");

        jLabel6.setText("Cinsiyet : ");

        jLabel7.setText("Telefon : ");

        jLabel8.setText("Poliklinik : ");

        btngrpCinsiyet_dd.add(rbErkek_dd);
        rbErkek_dd.setText("Erkek");
        rbErkek_dd.setActionCommand("E");

        btngrpCinsiyet_dd.add(rbKadın);
        rbKadın.setText("Kadın");
        rbKadın.setActionCommand("K");

        taAdres_dd.setColumns(20);
        taAdres_dd.setRows(5);
        jScrollPane2.setViewportView(taAdres_dd);

        cmbPoliklinik_dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPoliklinik_ddActionPerformed(evt);
            }
        });

        btnGuncelle_dd.setText("GÜNCELLE");
        btnGuncelle_dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelle_ddActionPerformed(evt);
            }
        });

        btnSil_dd.setText("SİL");
        btnSil_dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSil_ddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDoktorDuzenleLayout = new javax.swing.GroupLayout(pnlDoktorDuzenle);
        pnlDoktorDuzenle.setLayout(pnlDoktorDuzenleLayout);
        pnlDoktorDuzenleLayout.setHorizontalGroup(
            pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoktorDuzenleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDoktorDuzenleLayout.createSequentialGroup()
                        .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIsimSoyisim_dd)
                            .addComponent(tfTCKN_dd, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                    .addGroup(pnlDoktorDuzenleLayout.createSequentialGroup()
                        .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDoktorTelefon_dd)
                            .addComponent(dateDogumTarihi_dd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(pnlDoktorDuzenleLayout.createSequentialGroup()
                                .addComponent(rbErkek_dd)
                                .addGap(18, 18, 18)
                                .addComponent(rbKadın)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbPoliklinik_dd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlDoktorDuzenleLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnGuncelle_dd)
                        .addGap(18, 18, 18)
                        .addComponent(btnSil_dd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDoktorDuzenleLayout.setVerticalGroup(
            pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoktorDuzenleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIsimSoyisim_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTCKN_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dateDogumTarihi_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfDoktorTelefon_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbErkek_dd)
                    .addComponent(rbKadın))
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDoktorDuzenleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(pnlDoktorDuzenleLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPoliklinik_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(pnlDoktorDuzenleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuncelle_dd)
                    .addComponent(btnSil_dd))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDoktorlarLayout = new javax.swing.GroupLayout(pnlDoktorlar);
        pnlDoktorlar.setLayout(pnlDoktorlarLayout);
        pnlDoktorlarLayout.setHorizontalGroup(
            pnlDoktorlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoktorlarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDoktorlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDoktorlarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfArama))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlDoktorDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDoktorlarLayout.setVerticalGroup(
            pnlDoktorlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoktorlarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDoktorlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDoktorDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDoktorlarLayout.createSequentialGroup()
                        .addGroup(pnlDoktorlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlYeniDoktorEkle.setBackground(new java.awt.Color(255, 255, 255));
        pnlYeniDoktorEkle.setBorder(javax.swing.BorderFactory.createTitledBorder("Yeni Doktor Ekle"));

        jLabel9.setText("İsim Soyisim : ");

        jLabel10.setText("T.C Kimlik No : ");

        jLabel11.setText("Doğum Tarihi : ");

        jLabel12.setText("Adres : ");

        jLabel13.setText("Cinsiyet : ");

        jLabel14.setText("Telefon : ");

        jLabel15.setText("Poliklinik : ");

        tfTCKN_yd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTCKN_ydActionPerformed(evt);
            }
        });

        btngrpCinsiyet_yd.add(rbErkek_yd);
        rbErkek_yd.setText("Erkek");
        rbErkek_yd.setActionCommand("E");

        btngrpCinsiyet_yd.add(rbKadin_yd);
        rbKadin_yd.setText("Kadın");
        rbKadin_yd.setActionCommand("K");

        taAdres_yd.setColumns(20);
        taAdres_yd.setRows(5);
        jScrollPane3.setViewportView(taAdres_yd);

        btnEkle.setText("EKLE");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlYeniDoktorEkleLayout = new javax.swing.GroupLayout(pnlYeniDoktorEkle);
        pnlYeniDoktorEkle.setLayout(pnlYeniDoktorEkleLayout);
        pnlYeniDoktorEkleLayout.setHorizontalGroup(
            pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlYeniDoktorEkleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlYeniDoktorEkleLayout.createSequentialGroup()
                        .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIsımSoyisim_yd, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(tfTCKN_yd)))
                    .addGroup(pnlYeniDoktorEkleLayout.createSequentialGroup()
                        .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTelefon_yd)
                            .addComponent(dateDogumTarihi_yd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(pnlYeniDoktorEkleLayout.createSequentialGroup()
                                .addComponent(rbErkek_yd)
                                .addGap(18, 18, 18)
                                .addComponent(rbKadin_yd)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbPoliklinik_yd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlYeniDoktorEkleLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnEkle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlYeniDoktorEkleLayout.setVerticalGroup(
            pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlYeniDoktorEkleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfIsımSoyisim_yd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfTCKN_yd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(dateDogumTarihi_yd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfTelefon_yd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rbErkek_yd)
                    .addComponent(rbKadin_yd))
                .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlYeniDoktorEkleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(pnlYeniDoktorEkleLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlYeniDoktorEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPoliklinik_yd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(btnEkle)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel16.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/doctor-icon-1.png"))); // NOI18N
        jLabel16.setText("DOKTORLAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(521, 521, 521)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlDoktorlar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlYeniDoktorEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDoktorlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlYeniDoktorEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAramaActionPerformed

    private void btnGuncelle_ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelle_ddActionPerformed
        
        Boolean isEmpty = (tfIsimSoyisim_dd.getText() == null ) || (tfTCKN_dd.getText() == null) || (btngrpCinsiyet_dd.getSelection().getActionCommand() == null)
                || (cmbPoliklinik_dd.getSelectedItem() == null) || (dateDogumTarihi_dd.getDate() == null) || (taAdres_dd.getText() == null) || (tfDoktorTelefon_dd.getText() == null);
        
        if( isEmpty ){
            Helper.showMessage("fill");
        }else{
            Doktor yeniDoktor = new Doktor();
            yeniDoktor.setId(selectedDoktor.getId());
            yeniDoktor.setisimSoyisim(tfIsimSoyisim_dd.getText());
            yeniDoktor.setTckn(tfTCKN_dd.getText());
            yeniDoktor.setCinsiyet(btngrpCinsiyet_dd.getSelection().getActionCommand());
            yeniDoktor.setPoliklinikId(poliklinikIslemleri.PoliklinikToID(cmbPoliklinik_dd.getSelectedItem().toString()));
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String dogumTarihi = format.format(dateDogumTarihi_dd.getDate());
            yeniDoktor.setDogumTarihi(dogumTarihi);
            yeniDoktor.setAdres(taAdres_dd.getText());
            yeniDoktor.setTelefon(tfDoktorTelefon_dd.getText());
            
            if( doktorIslemleri.Guncelle(yeniDoktor) ){
                doktorlarTablo();
                Helper.showMessage("DOKTOR GÜNCELLENDİ.");

            }else{
                Helper.showMessage("HATA! Doktor Eklenemedi.");
            }
            
        }
        
    }//GEN-LAST:event_btnGuncelle_ddActionPerformed

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        
        Boolean isEmpty = (tfIsımSoyisim_yd.getText() == null ) || (tfTCKN_yd.getText() == null) || (btngrpCinsiyet_yd.getSelection().getActionCommand() == null)
                || (cmbPoliklinik_yd.getSelectedItem() == null) || (dateDogumTarihi_yd.getDate() == null) || (taAdres_yd.getText() == null) || (tfTelefon_yd.getText() == null);
        
        if( isEmpty ){
            Helper.showMessage("fill");
        }else{
            Doktor yeniDoktor = new Doktor();
            yeniDoktor.setisimSoyisim(tfIsımSoyisim_yd.getText());
            yeniDoktor.setTckn(tfTCKN_yd.getText());
            yeniDoktor.setCinsiyet(btngrpCinsiyet_yd.getSelection().getActionCommand());
            yeniDoktor.setPoliklinikId(poliklinikIslemleri.PoliklinikToID(cmbPoliklinik_yd.getSelectedItem().toString()));
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String dogumTarihi = format.format(dateDogumTarihi_yd.getDate());
            yeniDoktor.setDogumTarihi(dogumTarihi);
            yeniDoktor.setAdres(taAdres_yd.getText());
            yeniDoktor.setTelefon(tfTelefon_yd.getText());
            
            if( doktorIslemleri.Ekle(yeniDoktor) ){
                doktorlarTablo();
                Helper.showMessage("DOKTOR EKLENDİ.");
            }else{
                System.out.println("dadada");
                Helper.showMessage("HATA! Doktor Eklenemedi.");
            }
            
        }
 
    }//GEN-LAST:event_btnEkleActionPerformed

    private void tfTCKN_ydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTCKN_ydActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTCKN_ydActionPerformed

    private void cmbPoliklinik_ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPoliklinik_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPoliklinik_ddActionPerformed

    private void tblDoktorlarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoktorlarMouseClicked
        int id = ((int)tblDoktorlar.getValueAt(tblDoktorlar.getSelectedRow(), 0))-1;
        selectedDoktor = doktorlar.get(id);
        bilgiGetir(selectedDoktor);
    }//GEN-LAST:event_tblDoktorlarMouseClicked

    private void tfAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAramaKeyReleased
        String ifade = tfArama.getText();
        TableRowSorter<DefaultTableModel>  tableRowSorter = new TableRowSorter<DefaultTableModel>(tableModel);
        tblDoktorlar.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(ifade));
    }//GEN-LAST:event_tfAramaKeyReleased

    private void btnSil_ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSil_ddActionPerformed
       if(doktorIslemleri.Sil(selectedDoktor)){
           doktorlarTablo();
           Helper.showMessage("Doktor Silindi.");
       }else{
           Helper.showMessage("HATA! Doktor Silinemedi.");
       }
    }//GEN-LAST:event_btnSil_ddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorlarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorlarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorlarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorlarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorlarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGuncelle_dd;
    private javax.swing.JButton btnSil_dd;
    private javax.swing.ButtonGroup btngrpCinsiyet_dd;
    private javax.swing.ButtonGroup btngrpCinsiyet_yd;
    private javax.swing.JComboBox<String> cmbPoliklinik_dd;
    private javax.swing.JComboBox<String> cmbPoliklinik_yd;
    private com.toedter.calendar.JDateChooser dateDogumTarihi_dd;
    private com.toedter.calendar.JDateChooser dateDogumTarihi_yd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlDoktorDuzenle;
    private javax.swing.JPanel pnlDoktorlar;
    private javax.swing.JPanel pnlYeniDoktorEkle;
    private javax.swing.JRadioButton rbErkek_dd;
    private javax.swing.JRadioButton rbErkek_yd;
    private javax.swing.JRadioButton rbKadin_yd;
    private javax.swing.JRadioButton rbKadın;
    private javax.swing.JTextArea taAdres_dd;
    private javax.swing.JTextArea taAdres_yd;
    private javax.swing.JTable tblDoktorlar;
    private javax.swing.JTextField tfArama;
    private javax.swing.JTextField tfDoktorTelefon_dd;
    private javax.swing.JTextField tfIsimSoyisim_dd;
    private javax.swing.JTextField tfIsımSoyisim_yd;
    private javax.swing.JTextField tfTCKN_dd;
    private javax.swing.JTextField tfTCKN_yd;
    private javax.swing.JTextField tfTelefon_yd;
    // End of variables declaration//GEN-END:variables
}
