/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Doktor;
import javax.swing.table.DefaultTableModel;
import Model.*;
import Helper.*;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author turanozturk
 */
public class PolikliniklerGUI extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    PoliklinikIslemleri poliklinikIslemleri = new PoliklinikIslemleri();
    ArrayList<Poliklinik> poliklinikler;
    Poliklinik selectedPoliklinik;
    
    /**
     * Creates new form PolikliniklerGUI
     */
    public PolikliniklerGUI() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        tableModel = (DefaultTableModel)tblPoliklinikler.getModel();
        poliklinikTablo();
        selectedPoliklinik = poliklinikler.get(0);
        bilgiGetir();
        
    }
    
    public void poliklinikTablo(){
    
        tableModel.setRowCount(0);
        poliklinikler = poliklinikIslemleri.Listele("SELECT * FROM poliklinikler");
        int no = 0;
        for(Poliklinik poliklinik : poliklinikler){
            Object[] row = { no + 1 , poliklinik.getPoliklinikAdi()};
            tableModel.addRow(row);
            no++;
        }
        tblPoliklinikler.changeSelection(0, 0, false, false);
        selectedPoliklinik = poliklinikler.get(0);
        bilgiGetir();
        
    }
    
    public void bilgiGetir(){
        tfPoliklinikAdi_pd.setText(selectedPoliklinik.getPoliklinikAdi());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPoliklinikler = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfArama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoliklinikler = new javax.swing.JTable();
        pnlPoliklinikDuzenleSil = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfPoliklinikAdi_pd = new javax.swing.JTextField();
        btnPoliklinikGuncelle = new javax.swing.JButton();
        btnPoliklinikSil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfPoliklinikAdi_pe = new javax.swing.JTextField();
        btnEkle = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlPoliklinikler.setBackground(new java.awt.Color(255, 255, 255));
        pnlPoliklinikler.setBorder(javax.swing.BorderFactory.createTitledBorder("Poliklinikler"));

        jLabel1.setText("Arama : ");

        tfArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAramaKeyReleased(evt);
            }
        });

        tblPoliklinikler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Poliklinik"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPoliklinikler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPolikliniklerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPoliklinikler);
        if (tblPoliklinikler.getColumnModel().getColumnCount() > 0) {
            tblPoliklinikler.getColumnModel().getColumn(0).setResizable(false);
            tblPoliklinikler.getColumnModel().getColumn(1).setResizable(false);
        }

        pnlPoliklinikDuzenleSil.setBackground(new java.awt.Color(255, 255, 255));
        pnlPoliklinikDuzenleSil.setBorder(javax.swing.BorderFactory.createTitledBorder("Poliklinik Düzenle & Sil"));

        jLabel3.setText("Poliklinik Adı : ");

        btnPoliklinikGuncelle.setText("GÜNCELLE");
        btnPoliklinikGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliklinikGuncelleActionPerformed(evt);
            }
        });

        btnPoliklinikSil.setText("SİL");
        btnPoliklinikSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliklinikSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPoliklinikDuzenleSilLayout = new javax.swing.GroupLayout(pnlPoliklinikDuzenleSil);
        pnlPoliklinikDuzenleSil.setLayout(pnlPoliklinikDuzenleSilLayout);
        pnlPoliklinikDuzenleSilLayout.setHorizontalGroup(
            pnlPoliklinikDuzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoliklinikDuzenleSilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPoliklinikDuzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPoliklinikDuzenleSilLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPoliklinikAdi_pd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPoliklinikDuzenleSilLayout.createSequentialGroup()
                        .addComponent(btnPoliklinikGuncelle)
                        .addGap(18, 18, 18)
                        .addComponent(btnPoliklinikSil)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPoliklinikDuzenleSilLayout.setVerticalGroup(
            pnlPoliklinikDuzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoliklinikDuzenleSilLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlPoliklinikDuzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPoliklinikAdi_pd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnlPoliklinikDuzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPoliklinikGuncelle)
                    .addComponent(btnPoliklinikSil))
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Poliklinik Ekle"));

        jLabel4.setText("Poliklinik Adı : ");

        btnEkle.setText("EKLE");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEkle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfPoliklinikAdi_pe))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPoliklinikAdi_pe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEkle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPolikliniklerLayout = new javax.swing.GroupLayout(pnlPoliklinikler);
        pnlPoliklinikler.setLayout(pnlPolikliniklerLayout);
        pnlPolikliniklerLayout.setHorizontalGroup(
            pnlPolikliniklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolikliniklerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPolikliniklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPolikliniklerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfArama)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPolikliniklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPoliklinikDuzenleSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPolikliniklerLayout.setVerticalGroup(
            pnlPolikliniklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolikliniklerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlPolikliniklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPolikliniklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPolikliniklerLayout.createSequentialGroup()
                        .addComponent(pnlPoliklinikDuzenleSil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        jLabel2.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/poliklinik.png"))); // NOI18N
        jLabel2.setText(" POLİKLİNİK İŞLEMLERİ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPoliklinikler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pnlPoliklinikler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPoliklinikGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliklinikGuncelleActionPerformed
        if(tfPoliklinikAdi_pd.getText() == null){
            Helper.showMessage("fill");
        }else{
            Poliklinik edittedPoliklinik = new Poliklinik();
            edittedPoliklinik.setPoliklinikAdi(tfPoliklinikAdi_pd.getText());
            edittedPoliklinik.setPoliklinikID(selectedPoliklinik.getPoliklinikID());
            if(poliklinikIslemleri.Guncelle(edittedPoliklinik)){
                poliklinikTablo();
                Helper.showMessage("Poliklinik Güncellendi");
            }else{
                Helper.showMessage("HATA! Poliklinik Güncellenemedi.");
            }
        }
        
    }//GEN-LAST:event_btnPoliklinikGuncelleActionPerformed

    private void tblPolikliniklerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPolikliniklerMouseClicked
        int id = ((int)tblPoliklinikler.getValueAt(tblPoliklinikler.getSelectedRow(), 0))-1;
        selectedPoliklinik = poliklinikler.get(id);
        bilgiGetir();
    }//GEN-LAST:event_tblPolikliniklerMouseClicked

    private void btnPoliklinikSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliklinikSilActionPerformed
        if(poliklinikIslemleri.Sil(selectedPoliklinik)){
            poliklinikTablo();
            Helper.showMessage("Poliklinik Silindi.");
            selectedPoliklinik = poliklinikler.get(0);
            bilgiGetir();
        }else{
            Helper.showMessage("HATA! Poliklinik Silinemedi.");
        }
    }//GEN-LAST:event_btnPoliklinikSilActionPerformed

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        if(tfPoliklinikAdi_pe.getText() != null){
            Poliklinik poliklinik = new Poliklinik();
            poliklinik.setPoliklinikAdi(tfPoliklinikAdi_pe.getText());
            if(poliklinikIslemleri.Ekle(poliklinik)){
                poliklinikTablo();
                Helper.showMessage("Poliklinik Eklendi.");
                tfPoliklinikAdi_pe.setText("");
            }else{
                Helper.showMessage("HATA! Poliklinik Eklenemedi.");
            }
        }else{
            Helper.showMessage("fill");
        }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void tfAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAramaKeyReleased
        String ifade = tfArama.getText();
        TableRowSorter<DefaultTableModel>  tableRowSorter = new TableRowSorter<DefaultTableModel>(tableModel);
        tblPoliklinikler.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(ifade));
    }//GEN-LAST:event_tfAramaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolikliniklerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolikliniklerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolikliniklerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolikliniklerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolikliniklerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnPoliklinikGuncelle;
    private javax.swing.JButton btnPoliklinikSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlPoliklinikDuzenleSil;
    private javax.swing.JPanel pnlPoliklinikler;
    private javax.swing.JTable tblPoliklinikler;
    private javax.swing.JTextField tfArama;
    private javax.swing.JTextField tfPoliklinikAdi_pd;
    private javax.swing.JTextField tfPoliklinikAdi_pe;
    // End of variables declaration//GEN-END:variables
}
