/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Helper.*;
import Model.RandevuIslemleri;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.*;
import static View.RandevuVerGUI.poliklinikIslemleri;
import static View.RandevuVerGUI.selectedPoliklinik;
import static View.RandevuVerGUI.takvimIslemleri;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author turanozturk
 */
public class RandevuDuzenleGUI extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    RandevuIslemleri randevuIslemleri = new RandevuIslemleri();
    PoliklinikIslemleri poliklinikIslemleri = new PoliklinikIslemleri();
    DoktorIslemleri doktorIslemleri = new DoktorIslemleri();
    TakvimIslemleri takvimIslemleri = new TakvimIslemleri();
    ArrayList<Randevu> randevular = new ArrayList<Randevu>();
    Randevu selectedRandevu;
    Randevu edittedRandevu = new Randevu();
    Poliklinik edittedPoliklinik;
    Doktor selectedDoktor;
   
    /**
     * Creates new form RandevuDuzenleGUI
     */
    public RandevuDuzenleGUI() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        randevuTablo();
        
    }
    
    public void randevuTablo(){
    
        tableModel.setRowCount(0);
        randevular = randevuIslemleri.Listele("SELECT * FROM randevular");
        int no = 0;
        for(Randevu randevu : randevular){
           Object[] row = {no+1 , randevu.getHasta().getisimSoyisim(), randevu.getHasta().getTckn(), randevu.getTarih(), randevu.getSaat() , poliklinikIslemleri.idToPoliklinik(randevu.getPoliklinikId()), doktorIslemleri.idToDoktor(randevu.getDoktorId())};
           tableModel.addRow(row);
           no++;
        }
        tblRandevular.changeSelection(0, 0, false, false);
        selectedRandevu = randevular.get(0);
        nesneKopyala(selectedRandevu, edittedRandevu);
        bilgileriGetir(edittedRandevu);
        cmbSaat.setSelectedItem(selectedRandevu.getSaat());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlSol = new javax.swing.JPanel();
        pnlArama = new javax.swing.JPanel();
        lblArama = new javax.swing.JLabel();
        tfArama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRandevular = new javax.swing.JTable();
        pnlSag = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfTCKN = new javax.swing.JTextField();
        tfHastaAdi = new javax.swing.JTextField();
        rbErkek = new javax.swing.JRadioButton();
        rbKadin = new javax.swing.JRadioButton();
        tfTelefon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAdres = new javax.swing.JTextArea();
        ArrayList<Poliklinik> polikliniklerArrayList = poliklinikIslemleri.Listele("SELECT * FROM poliklinikler");
        String[] poliklinikAdlari = new String[polikliniklerArrayList.size()];
        for(int i = 0; i < poliklinikAdlari.length; i++){
            poliklinikAdlari[i] = polikliniklerArrayList.get(i).getPoliklinikAdi();
        }
        Arrays.sort(poliklinikAdlari);
        cmbPoliklinik = new javax.swing.JComboBox<>();
        cmbDoktor = new javax.swing.JComboBox<>();
        cmbSaat = new javax.swing.JComboBox<>();
        btnSil = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        dateDogumTarihi = new com.toedter.calendar.JDateChooser();
        dateChoose = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlSol.setBackground(new java.awt.Color(255, 255, 255));
        pnlSol.setBorder(javax.swing.BorderFactory.createTitledBorder("Randevular"));

        pnlArama.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblArama.setText("Arama : ");

        tfArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAramaActionPerformed(evt);
            }
        });
        tfArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAramaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlAramaLayout = new javax.swing.GroupLayout(pnlArama);
        pnlArama.setLayout(pnlAramaLayout);
        pnlAramaLayout.setHorizontalGroup(
            pnlAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAramaLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(lblArama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfArama, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        pnlAramaLayout.setVerticalGroup(
            pnlAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfArama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArama))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblRandevular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Hasta", "T.C. Kimlik No", "Tarih", "Saat", "Poliklinik", "Doktor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRandevular.setRowHeight(20);
        tblRandevular.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblRandevular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRandevularMouseClicked(evt);
            }
        });
        tblRandevular.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblRandevularPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblRandevular);
        if (tblRandevular.getColumnModel().getColumnCount() > 0) {
            tblRandevular.getColumnModel().getColumn(0).setResizable(false);
            tblRandevular.getColumnModel().getColumn(1).setResizable(false);
        }
        tableModel = (DefaultTableModel)tblRandevular.getModel();

        javax.swing.GroupLayout pnlSolLayout = new javax.swing.GroupLayout(pnlSol);
        pnlSol.setLayout(pnlSolLayout);
        pnlSolLayout.setHorizontalGroup(
            pnlSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlArama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        pnlSolLayout.setVerticalGroup(
            pnlSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
        );

        pnlSag.setBackground(new java.awt.Color(255, 255, 255));
        pnlSag.setBorder(javax.swing.BorderFactory.createTitledBorder("Randevu Düzenle & Sil"));

        jLabel2.setText("Hasta Adı : ");

        jLabel3.setText("T.C Kimlik No : ");

        jLabel4.setText("Doğum Tarihi :");

        jLabel5.setText("Cinsiyet : ");

        jLabel6.setText("Telefon : ");

        jLabel7.setText("Adres : ");

        jLabel8.setText("Poliklinik : ");

        jLabel9.setText("Doktor : ");

        jLabel10.setText("Randevu Tarihi : ");

        jLabel11.setText("Randevu Saati : ");

        buttonGroup1.add(rbErkek);
        rbErkek.setText("ERKEK");
        rbErkek.setActionCommand("E");
        rbErkek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbErkekActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKadin);
        rbKadin.setText("KADIN");
        rbKadin.setActionCommand("K");

        taAdres.setColumns(20);
        taAdres.setRows(5);
        jScrollPane2.setViewportView(taAdres);

        cmbPoliklinik.setModel(new javax.swing.DefaultComboBoxModel<>(poliklinikAdlari));
        cmbPoliklinik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPoliklinikActionPerformed(evt);
            }
        });

        cmbDoktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDoktorActionPerformed(evt);
            }
        });

        cmbSaat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSaatActionPerformed(evt);
            }
        });

        btnSil.setText("SİL");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGuncelle.setText("GÜNCELLE");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        dateChoose.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChoosePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlSagLayout = new javax.swing.GroupLayout(pnlSag);
        pnlSag.setLayout(pnlSagLayout);
        pnlSagLayout.setHorizontalGroup(
            pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSagLayout.createSequentialGroup()
                        .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSagLayout.createSequentialGroup()
                        .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPoliklinik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSaat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDoktor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSagLayout.createSequentialGroup()
                        .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTCKN)
                            .addComponent(tfHastaAdi)
                            .addGroup(pnlSagLayout.createSequentialGroup()
                                .addComponent(rbErkek)
                                .addGap(18, 18, 18)
                                .addComponent(rbKadin))
                            .addComponent(tfTelefon)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(dateDogumTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSagLayout.setVerticalGroup(
            pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSagLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfHastaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTCKN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dateDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbErkek)
                    .addComponent(rbKadin))
                .addGap(24, 24, 24)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbPoliklinik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(dateChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlSagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSil)
                    .addComponent(btnGuncelle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/edit-file-icon.png"))); // NOI18N
        jLabel1.setText("RANDEVU İŞLEMLERİ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(pnlSag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbErkekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbErkekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbErkekActionPerformed

    private void tblRandevularPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblRandevularPropertyChange

    }//GEN-LAST:event_tblRandevularPropertyChange

    private void tfAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAramaKeyReleased
        String ifade = tfArama.getText();
        TableRowSorter<DefaultTableModel>  tableRowSorter = new TableRowSorter<DefaultTableModel>(tableModel);
        tblRandevular.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(ifade));
    }//GEN-LAST:event_tfAramaKeyReleased

    private void tblRandevularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRandevularMouseClicked
        int selectedRow = (int)tblRandevular.getValueAt(tblRandevular.getSelectedRow(), 0);
        selectedRandevu = randevular.get(selectedRow - 1);
        nesneKopyala(selectedRandevu, edittedRandevu);
        bilgileriGetir(edittedRandevu);
        
    }//GEN-LAST:event_tblRandevularMouseClicked

    private void cmbPoliklinikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPoliklinikActionPerformed
        cmbDoktor.removeAllItems();
        selectedPoliklinik = poliklinikIslemleri.Listele("SELECT * FROM poliklinikler WHERE poliklinik_adi = '"+ cmbPoliklinik.getSelectedItem() +"' ").get(0);
        edittedRandevu.setPoliklinikId(selectedPoliklinik.getPoliklinikID());
        ArrayList<Doktor> doktorlarArrayList = doktorIslemleri.Listele("SELECT * FROM doktorlar WHERE poliklinik_id = '"+ selectedPoliklinik.getPoliklinikID() +"' ");
        for(int i = 0; i < doktorlarArrayList.size(); i++){
            cmbDoktor.addItem(doktorlarArrayList.get(i).getisimSoyisim());
        }
    }//GEN-LAST:event_cmbPoliklinikActionPerformed

    private void cmbDoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDoktorActionPerformed
        if(cmbDoktor.getSelectedItem() != null)
        selectedDoktor = doktorIslemleri.Listele("SELECT * FROM doktorlar WHERE isim_soyisim = '"+ cmbDoktor.getSelectedItem() +"' ").get(0);
        edittedRandevu.setDoktorId(selectedDoktor.getId());
    }//GEN-LAST:event_cmbDoktorActionPerformed

    private void dateChoosePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChoosePropertyChange
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String date = "";
        cmbSaat.removeAllItems();
        if(dateChoose.getDate() != null){
        date = sdf.format(dateChoose.getDate());
        edittedRandevu.setTarih(date);
            if(date.equals("")){}else{
             ArrayList<String> uygunSaatlerArrayList = takvimIslemleri.uygunSaatler(edittedRandevu.getTarih(),selectedRandevu.getTarih(), edittedRandevu.getDoktorId(), selectedRandevu.getDoktorId(), takvimIslemleri.saatToInt( selectedRandevu.getSaat() ) );
                System.out.println("..."+ uygunSaatlerArrayList.size());
             for(String uygunSaat : uygunSaatlerArrayList){
             cmbSaat.addItem(uygunSaat);
        }
            }
        }
    }//GEN-LAST:event_dateChoosePropertyChange

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        
        if(randevuIslemleri.Sil(selectedRandevu)){
            randevuTablo();
            Helper.showMessage("RANDEVU SİLİNDİ.");
        }else{
            Helper.showMessage("HATA..! RANDEVU SİLİNEMEDİ.");
        }
         
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        String hastaIsimSoyisim = tfHastaAdi.getText();
        String hastaTCKN = tfTCKN.getText();
        String hastaTel = tfTelefon.getText();
        String hastaAdres = taAdres.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String hastaDogumTarihi = "";
        hastaDogumTarihi = sdf.format(dateDogumTarihi.getDate());
        String hastaCinsiyet = buttonGroup1.getSelection().getActionCommand();
        if( hastaIsimSoyisim.equals("") || (hastaTCKN.equals("")) || (hastaTel.equals("")) || (hastaAdres.equals("")) ){
            Helper.showMessage("fill");
        }else{
            
            if( (edittedRandevu.getDoktorId() == 0) || (edittedRandevu.getPoliklinikId() == 0) || edittedRandevu.getSaat().equals("") || edittedRandevu.getTarih().equals("") ){
               Helper.showMessage("fill");
            }else{
                
                edittedRandevu.getHasta().setisimSoyisim(hastaIsimSoyisim);
                edittedRandevu.getHasta().setTckn(hastaTCKN);
                edittedRandevu.getHasta().setTelefon(hastaTel);
                edittedRandevu.getHasta().setAdres(hastaAdres);
                edittedRandevu.getHasta().setDogumTarihi(hastaDogumTarihi);
                edittedRandevu.getHasta().setCinsiyet(hastaCinsiyet);

                
                if( randevuIslemleri.Guncelle(edittedRandevu) ){
                    
                    randevuTablo();
                    Helper.showMessage("RANDEVU GÜNCELLENDİ.");

                }else{
                    Helper.showMessage("HATA! Randevu Eklenemedi.");
                }
                
            }
            
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void cmbSaatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSaatActionPerformed
        if( cmbSaat.getSelectedItem() == null ){
        
        }else{
            edittedRandevu.setSaat(cmbSaat.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbSaatActionPerformed

    private void tfAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAramaActionPerformed

    private void bilgileriGetir(Randevu randevu){
        
        tfHastaAdi.setText(randevu.getHasta().getisimSoyisim());
        tfTCKN.setText(randevu.getHasta().getTckn());
        String stringDogumTarihi = randevu.getHasta().getDogumTarihi();
        SimpleDateFormat formatDT = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date dogumTarihi = formatDT.parse(stringDogumTarihi);
            dateDogumTarihi.setDate(dogumTarihi);
        } catch (ParseException ex) {
            Logger.getLogger(RandevuDuzenleGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(randevu.getHasta().getCinsiyet().equals("E")){
            rbErkek.setSelected(true);
        }else{
            rbKadin.setSelected(true);
        }
        tfTelefon.setText(randevu.getHasta().getTelefon());
        taAdres.setText(randevu.getHasta().getAdres());
        cmbPoliklinik.setSelectedItem(poliklinikIslemleri.idToPoliklinik(randevu.getPoliklinikId()));
        
        ArrayList<Doktor> doktorlar = doktorIslemleri.Listele("SELECT * FROM doktorlar WHERE poliklinik_id = '"+ randevu.getPoliklinikId() +"' ");
        cmbDoktor.removeAllItems();
        for(Doktor doktor : doktorlar){
            cmbDoktor.addItem(doktor.getisimSoyisim());
        }
        cmbDoktor.setSelectedItem(doktorIslemleri.idToDoktor(randevu.getDoktorId()));
        String stringDate = new String();
        stringDate = randevu.getTarih();
        System.out.println(stringDate);
        SimpleDateFormat formatRT = new SimpleDateFormat("dd/MM/yyyy");
        Date randevuTarihi;
        try {
            randevuTarihi = formatRT.parse(stringDate);
            dateChoose.setDate(randevuTarihi);
        } catch (ParseException ex) {
            Logger.getLogger(RandevuDuzenleGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        cmbSaat.removeAllItems();
        ArrayList<String> uygunSaatler = takvimIslemleri.uygunSaatler(randevu.getTarih(), randevu.getDoktorId(), takvimIslemleri.saatToInt(selectedRandevu.getSaat()));
        for(String saat : uygunSaatler){
            cmbSaat.addItem(saat);
        }
        System.out.println("SAAT : " + randevu.getSaat());
        cmbSaat.setSelectedItem(selectedRandevu.getSaat());
        
    }
    
    private void nesneKopyala(Randevu randevuMain, Randevu randevuCoppied){
        
        randevuCoppied.getHasta().setisimSoyisim(randevuMain.getHasta().getisimSoyisim());
        randevuCoppied.getHasta().setTckn(randevuMain.getHasta().getTckn());
        randevuCoppied.getHasta().setTelefon(randevuMain.getHasta().getTelefon());
        randevuCoppied.getHasta().setCinsiyet(randevuMain.getHasta().getCinsiyet());
        randevuCoppied.getHasta().setDogumTarihi(randevuMain.getHasta().getDogumTarihi());
        randevuCoppied.getHasta().setAdres(randevuMain.getHasta().getAdres());
        randevuCoppied.setDoktorId(randevuMain.getDoktorId());
        randevuCoppied.setPoliklinikId(randevuMain.getPoliklinikId());
        randevuCoppied.setSaat(randevuMain.getSaat());
        randevuCoppied.setTarih(randevuMain.getTarih());
        randevuCoppied.setId(randevuMain.getId());
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandevuDuzenleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandevuDuzenleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandevuDuzenleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandevuDuzenleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

  
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RandevuDuzenleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnSil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbDoktor;
    private javax.swing.JComboBox<String> cmbPoliklinik;
    private javax.swing.JComboBox<String> cmbSaat;
    private com.toedter.calendar.JDateChooser dateChoose;
    private com.toedter.calendar.JDateChooser dateDogumTarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArama;
    private javax.swing.JPanel pnlArama;
    private javax.swing.JPanel pnlSag;
    private javax.swing.JPanel pnlSol;
    private javax.swing.JRadioButton rbErkek;
    private javax.swing.JRadioButton rbKadin;
    private javax.swing.JTextArea taAdres;
    private javax.swing.JTable tblRandevular;
    private javax.swing.JTextField tfArama;
    private javax.swing.JTextField tfHastaAdi;
    private javax.swing.JTextField tfTCKN;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
