/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import Helper.*;
import java.util.Arrays;
import javax.swing.SwingUtilities;

/**
 *
 * @author turanozturk
 */
public class RandevuVerGUI extends javax.swing.JFrame {

    public static PoliklinikIslemleri poliklinikIslemleri = new PoliklinikIslemleri();
    DoktorIslemleri doktorIslemleri = new DoktorIslemleri();
    public static Poliklinik selectedPoliklinik = null;
    Doktor selectedDoktor;
    ArrayList<String> doktorAdlari = new ArrayList<String>();
    private static Randevu randevu = new Randevu();
    public static TakvimIslemleri takvimIslemleri = new TakvimIslemleri();
    private static Hasta hasta = new Hasta();
    private static RandevuIslemleri randevuIslemleri = new RandevuIslemleri();
    public String selectedString = "";
    
    /**
     * Creates new form RandevuVerGUI
     */
    public RandevuVerGUI() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        btnGrpCinsiyet = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        pnlPoliklinikDoktor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ArrayList<Poliklinik> polikliniklerArrayList = poliklinikIslemleri.Listele("SELECT * FROM poliklinikler");
        String[] poliklinikAdlari = new String[polikliniklerArrayList.size()];
        for(int i = 0; i < poliklinikAdlari.length; i++){
            poliklinikAdlari[i] = polikliniklerArrayList.get(i).getPoliklinikAdi();
        }
        Arrays.sort(poliklinikAdlari);
        cmbPoliklinik = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        String[] doktorAd = new String[doktorAdlari.size()];
        for( int i = 0; i < doktorAd.length; i++ ){
            doktorAd[i] = doktorAdlari.get(i);
        }
        cmbDoktor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbSaat = new javax.swing.JComboBox<>();
        dateChoose = new com.toedter.calendar.JDateChooser();
        pnlHasta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_hastaIsimSoyisim = new javax.swing.JTextField();
        tf_HastaTckn = new javax.swing.JTextField();
        tf_HastaTel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_HastaAdres = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        dateDogumTarihi = new com.toedter.calendar.JDateChooser();
        lblCinsiyet = new javax.swing.JLabel();
        rbErkek = new javax.swing.JRadioButton();
        rbKadin = new javax.swing.JRadioButton();
        btnRandevuOnay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASTANE v1");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlPoliklinikDoktor.setBackground(new java.awt.Color(255, 255, 255));
        pnlPoliklinikDoktor.setBorder(javax.swing.BorderFactory.createTitledBorder("Poliklinik & Doktor Seçimi"));

        jLabel5.setText("Poliklinik : ");

        cmbPoliklinik.setModel(new javax.swing.DefaultComboBoxModel<>(poliklinikAdlari));
        cmbPoliklinik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbPoliklinik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPoliklinikActionPerformed(evt);
            }
        });

        jLabel6.setText("Doktor : ");

        cmbDoktor.setModel(new javax.swing.DefaultComboBoxModel<>(doktorAd));
        cmbDoktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDoktorActionPerformed(evt);
            }
        });

        jLabel7.setText("Tarih : ");

        jLabel8.setText("Saat : ");

        cmbSaat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSaat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSaatActionPerformed(evt);
            }
        });

        dateChoose.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChoosePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlPoliklinikDoktorLayout = new javax.swing.GroupLayout(pnlPoliklinikDoktor);
        pnlPoliklinikDoktor.setLayout(pnlPoliklinikDoktorLayout);
        pnlPoliklinikDoktorLayout.setHorizontalGroup(
            pnlPoliklinikDoktorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoliklinikDoktorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPoliklinikDoktorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPoliklinikDoktorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dateChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSaat, 0, 249, Short.MAX_VALUE)
                    .addComponent(cmbDoktor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPoliklinik, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlPoliklinikDoktorLayout.setVerticalGroup(
            pnlPoliklinikDoktorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoliklinikDoktorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlPoliklinikDoktorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbPoliklinik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPoliklinikDoktorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlPoliklinikDoktorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dateChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPoliklinikDoktorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        cmbPoliklinik.setSelectedIndex(0);
        selectedDoktor = doktorIslemleri.Listele("SELECT * FROM doktorlar WHERE isim_soyisim = '"+ cmbDoktor.getSelectedItem() +"' ").get(0);
        randevu.setDoktorId(selectedDoktor.getId());
        dateChoose.setDate(new Date());

        pnlHasta.setBackground(new java.awt.Color(255, 255, 255));
        pnlHasta.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasta Bilgileri"));

        jLabel1.setText("İsim Soyisim : ");

        jLabel3.setText("TC Kimlik No : ");

        jLabel4.setText("Telefon : ");

        tf_HastaTel.setText("+90");

        jLabel2.setText("Adres : ");

        tf_HastaAdres.setColumns(20);
        tf_HastaAdres.setRows(5);
        jScrollPane1.setViewportView(tf_HastaAdres);

        jLabel9.setText("Doğum Tarihi : ");

        lblCinsiyet.setText("Cinsiyet : ");

        btnGrpCinsiyet.add(rbErkek);
        rbErkek.setText("ERKEK");
        rbErkek.setActionCommand("E");
        rbErkek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbErkekActionPerformed(evt);
            }
        });

        btnGrpCinsiyet.add(rbKadin);
        rbKadin.setText("KADIN");
        rbKadin.setActionCommand("K");
        rbKadin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKadinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHastaLayout = new javax.swing.GroupLayout(pnlHasta);
        pnlHasta.setLayout(pnlHastaLayout);
        pnlHastaLayout.setHorizontalGroup(
            pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHastaLayout.createSequentialGroup()
                .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlHastaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateDogumTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(tf_hastaIsimSoyisim)
                            .addComponent(tf_HastaTckn)))
                    .addGroup(pnlHastaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lblCinsiyet)
                            .addComponent(jLabel2))
                        .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHastaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rbErkek)
                                .addGap(18, 18, 18)
                                .addComponent(rbKadin))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHastaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_HastaTel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlHastaLayout.setVerticalGroup(
            pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHastaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_hastaIsimSoyisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_HastaTckn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(dateDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCinsiyet)
                    .addComponent(rbErkek)
                    .addComponent(rbKadin))
                .addGap(18, 18, 18)
                .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_HastaTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRandevuOnay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Accept-icon.png"))); // NOI18N
        btnRandevuOnay.setText("RANDEVUYU ONAYLA");
        btnRandevuOnay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRandevuOnay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRandevuOnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandevuOnayActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel10.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/turanozturk/Desktop/JAVA PROJEE/HastaneRandevu/src/View/Add-Folder-icon.png")); // NOI18N
        jLabel10.setText("RANDEVU VER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(371, 371, 371))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlPoliklinikDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(pnlHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRandevuOnay, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPoliklinikDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnRandevuOnay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void cmbPoliklinikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPoliklinikActionPerformed
        cmbDoktor.removeAllItems();
        selectedPoliklinik = poliklinikIslemleri.Listele("SELECT * FROM poliklinikler WHERE poliklinik_adi = '"+ cmbPoliklinik.getSelectedItem() +"' ").get(0);
        randevu.setPoliklinikId(selectedPoliklinik.getPoliklinikID());
        ArrayList<Doktor> doktorlarArrayList = doktorIslemleri.Listele("SELECT * FROM doktorlar WHERE poliklinik_id = '"+ selectedPoliklinik.getPoliklinikID() +"' ");
        if(doktorlarArrayList.size() != 0){
            for(int i = 0; i < doktorlarArrayList.size(); i++){
                cmbDoktor.addItem(doktorlarArrayList.get(i).getisimSoyisim());
            }
        }
        
    }//GEN-LAST:event_cmbPoliklinikActionPerformed

    private void cmbDoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDoktorActionPerformed
        if(cmbDoktor.getSelectedItem() != null)
        selectedDoktor = doktorIslemleri.Listele("SELECT * FROM doktorlar WHERE isim_soyisim = '"+ cmbDoktor.getSelectedItem() +"' ").get(0);
        randevu.setDoktorId(selectedDoktor.getId());
    }//GEN-LAST:event_cmbDoktorActionPerformed

    private void dateChoosePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChoosePropertyChange
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String date = "";
        cmbSaat.removeAllItems();
        if(dateChoose.getDate() != null){
        date = sdf.format(dateChoose.getDate());
        randevu.setTarih(date);
            if(date.equals("")){}else{
             ArrayList<String> uygunSaatlerArrayList = takvimIslemleri.uygunSaatler(date,randevu.getDoktorId());
                System.out.println("..."+ uygunSaatlerArrayList.size());
             for(String uygunSaat : uygunSaatlerArrayList){
             cmbSaat.addItem(uygunSaat);
        }
            }
        }
    }//GEN-LAST:event_dateChoosePropertyChange

    private void btnRandevuOnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandevuOnayActionPerformed
        
        String hastaIsimSoyisim = tf_hastaIsimSoyisim.getText();
        String hastaTCKN = tf_HastaTckn.getText();
        String hastaTel = tf_HastaTel.getText();
        String hastaAdres = tf_HastaAdres.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String hastaDogumTarihi = "";
        hastaDogumTarihi = sdf.format(dateDogumTarihi.getDate());
        String hastaCinsiyet = btnGrpCinsiyet.getSelection().getActionCommand();
        System.out.println(hastaCinsiyet);
        if( hastaIsimSoyisim.equals("") || (hastaTCKN.equals("")) || (hastaTel.equals("")) || (hastaAdres.equals("")) ){
            Helper.showMessage("fill");
        }else{
            
            if( (randevu.getDoktorId() == 0) || (randevu.getPoliklinikId() == 0) || randevu.getSaat().equals("") || randevu.getTarih().equals("") ){
               Helper.showMessage("fill");
            }else{
                
                hasta.setisimSoyisim(hastaIsimSoyisim);
                hasta.setTckn(hastaTCKN);
                hasta.setTelefon(hastaTel);
                hasta.setAdres(hastaAdres);
                hasta.setDogumTarihi(hastaDogumTarihi);
                hasta.setCinsiyet(hastaCinsiyet);
                randevu.setHasta(hasta);
                
                if( randevuIslemleri.Ekle(randevu) ){
                    Helper.showMessage("RANDEVU BAŞARI İLE EKLENDİ");
                    
                    tf_hastaIsimSoyisim.setText("");
                    tf_HastaTckn.setText("");
                    tf_HastaTel.setText("");
                    tf_HastaAdres.setText("");
                    cmbPoliklinik.setSelectedIndex(0);
                    selectedDoktor = doktorIslemleri.Listele("SELECT * FROM doktorlar WHERE isim_soyisim = '"+ cmbDoktor.getSelectedItem() +"' ").get(0);
                    randevu.setDoktorId(selectedDoktor.getId());
                    dateChoose.setDate(new Date());

                    
                }else{
                    Helper.showMessage("HATA! Randevu Eklenemedi.");
                }
                
            }
            
        }
        
    }//GEN-LAST:event_btnRandevuOnayActionPerformed

    private void cmbSaatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSaatActionPerformed
       
        if( cmbSaat.getSelectedItem() == null ){
        
        }else{
            randevu.setSaat(cmbSaat.getSelectedItem().toString());
        }
        
    }//GEN-LAST:event_cmbSaatActionPerformed

    private void rbErkekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbErkekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbErkekActionPerformed

    private void rbKadinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKadinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKadinActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandevuVerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandevuVerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandevuVerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandevuVerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RandevuVerGUI().setVisible(true);
            }
        });
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpCinsiyet;
    private javax.swing.JButton btnRandevuOnay;
    private javax.swing.JComboBox<String> cmbDoktor;
    private javax.swing.JComboBox<String> cmbPoliklinik;
    private javax.swing.JComboBox<String> cmbSaat;
    private com.toedter.calendar.JDateChooser dateChoose;
    private com.toedter.calendar.JDateChooser dateDogumTarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblCinsiyet;
    private javax.swing.JPanel pnlHasta;
    private javax.swing.JPanel pnlPoliklinikDoktor;
    private javax.swing.JRadioButton rbErkek;
    private javax.swing.JRadioButton rbKadin;
    private javax.swing.JTextArea tf_HastaAdres;
    private javax.swing.JTextField tf_HastaTckn;
    private javax.swing.JTextField tf_HastaTel;
    private javax.swing.JTextField tf_hastaIsimSoyisim;
    // End of variables declaration//GEN-END:variables
}
